# -*- coding: utf-8 -*-
"""YELP_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rr7iW0W2tJqn17WOlq9WpSXnFp9KwwUw
"""

!python -m pip install requests

import requests

def fetch_yelp_data(api_key, term="renewable energy", location="New York City", limit=20, sort_by="best_match"):
    """
    Fetches business data from Yelp's API based on search criteria.

    Parameters:
        api_key (str): Your Yelp API key.
        term (str): Search term, e.g., "renewable energy".
        location (str): Location to search in, e.g., "New York City".
        limit (int): Maximum number of results to fetch.
        sort_by (str): Sort order, e.g., "best_match", "rating", "review_count".

    Returns:
        list: A list of dictionaries with business names, images, coordinates, links, and review counts.
    """
    url = f"https://api.yelp.com/v3/businesses/search?term={term}&location={location}&sort_by={sort_by}&limit={limit}"
    headers = {
        "accept": "application/json",
        "Authorization": f"Bearer {api_key}"
    }

    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        print(f"Failed to fetch data: {response.status_code} - {response.text}")
        return []

    data = response.json()
    businesses = [
        {
            "name": business["name"],
            "image_url": business.get("image_url"),
            "coordinates": business["coordinates"],
            "link": business.get("url"),
            "review_count": business.get("review_count")
        }
        for business in data.get("businesses", [])
    ]
    return businesses

API_KEY = '_WRbNCTbDokxy_wfb5q_8dlFN0ZOMyaB4PTZUxiQZVqHRi29zPpVyyduIGbem_m7XIy9oXw408Cu0LcKTncaTnMOeZ2k2-jcFANJAfjZbZ6bAoWXgZ-hTVTcI2lrZnYx'

results = fetch_yelp_data(API_KEY)


for business in results:
    print(business)